### PR TITLE
Automatically build & draft release when git push.

### PR DESCRIPTION
**Pull request by lwd-temp**
Automatically build webpacks for each language & draft release when git push.

### CODE REVIEW

**Comment by lwd-temp** [comment]
It seems that `--define:global=window` should be set in the command line to refer `genshindb.js` in the browser, otherwise `Uncaught ReferenceError: global is not defined` .

**Comment by theBowja** [comment]
node scripts use `global` while browsers use `window`. 

Inside my webpack.config.js, I have the target set to `node`. Probably the output will become `window` if you set target to `web` or idk something else. 

Using `<script src="genshindb.js"></script>` is definitely valid but not ideal since genshindb is more than 20MB uncompressed. Unfortunately, due to the way my project is setup, I can't figure out how to integrate webpack's tree shaking to shake off unused data.

I recommend:
compressing static pages
or dynamically loading genshindb based on language
or cutting out unused folders
or somehow extracting only the data you need
or using some web api
\- https://genshin-db-api.vercel.app/api/folders
\- https://genshin-db-api.vercel.app/api/languages
\- https://genshin-db-api.vercel.app/api/characters?query=hutao&resultLanguage=jap&queryLanguages=english,jap
\- I didn't work very hard on this web api so make an issue if you find problems

**Comment by theBowja** [comment]
The idea is good but I don't think I can accept this PR. Everyone has different use cases unfortunately. There doesn't seem to be a one-size-fits-all solution so it's probably better for each user to figure out the build process themselves?

Unless you have some ideas? I don't know much about build setup tbh.

**Comment by lwd-temp** [comment]
Since directly using `<script src="genshindb.js"></script>` is not encouraged, it's not very supportive to provide built webpack.
GitHub Actions doesn't support dynamically customized build. I'm afraid that building for each language is the best that Actions could do.

**Pull request closed without merging**
