### PR TITLE
fix: some broken icons

### PR DESCRIPTION
**Pull request by tractorcow**
No fixes for the side icons sorry, will look those up later

### CODE REVIEW

**Comment by theBowja** [comment]
man. why did they change their image links

**Comment by tractorcow** [comment]
Probably because they are new characters, they could be tweaking the imagese.

**Comment by tractorcow** [comment]
It's not appropriate to hotlink from the wiki, but here are the side images:
- https://static.wikia.nocookie.net/gensin-impact/images/1/16/Lynette_Side_Icon.png
- https://static.wikia.nocookie.net/gensin-impact/images/2/21/Freminet_Side_Icon.png
- https://static.wikia.nocookie.net/gensin-impact/images/6/6a/Lyney_Side_Icon.png
- https://static.wikia.nocookie.net/gensin-impact/images/1/1b/Kirara_Side_Icon.png

Need to find the hoyoverse static link

**Comment by tractorcow** [comment]
It might be ok to link directly to wiki. Reference:
 - https://genshin-impact.fandom.com/wiki/Genshin_Impact_Wiki:Community_Rules
 - https://www.fandom.com/terms-of-use
 - https://www.fandom.com/licensing

Does not prohibit hotlinking. I don't want to make the wrong call here though. :)

**Comment by theBowja** [comment]
i kinda want to delete hoyoverse and wikia image links. they dont have a standard format so i'll have to manually update them and i basically dont want to do that

**Comment by tractorcow** [comment]
Is it worth us shifting the images into its own repo (e.g. genshin-db-data or a new genshin-db-images)?

**Comment by theBowja** [comment]
well i just need to work on being able to extract the images myself from the game. then i dont need external image urls at all

**Comment by ReadySetMutive** [comment]
> well i just need to work on being able to extract the images myself from the game. then i dont need external image urls at all

I am unsure of how to do it directly from the game but there is a way to get pngs or better links of the pictures from genshin wiki.

For this example I will be trying to get Amber's character icon.

1. Go to genshin wiki's Character List Page (https://genshin-impact.fandom.com/wiki/Character/List)
2. Scroll down until you see Amber's entry. Right click over her image icon and click inspect.
3. You should see an  tag. Double click the src link (https://static.wikia.nocookie.net/gensin-impact/images/7/75/Amber_Icon.png/revision/latest/scale-to-width-down/50?cb=20210213161233) to copy and paste it into a new browser tab. Don't hit enter, image is too small but we can change that.
4. remove revision/latest/scale-to-width-down/50?cb=20210213161233 from the url. You should now get a bigger image of amber's icon. You can now use this link in the database for amber's icon. 

IF YOU WANT IT AS A PNG.
5. Download the .webp file by right clicking the iamge and doing save as. 
6. Rename the .webp part of the file as .png and Now you have a png of Amber's Icon with the game's file name for it. 

Its a bit of a workaround since genshin encodes their files but this is the next best thing. It should also be rather simple to automate it using python webscraping scripts if you every want to do that as well. Hope this helps!

**Comment by theBowja** [comment]
Wikia images are kinda unreliable because they usually have to wait until after the patch drops to add the image. And if they update the image, it'll change the version number in the URL thus invalidating all previous image links.

**Pull request merged**
