### PR TITLE
Added new recipes function.

### PR DESCRIPTION
**Pull request by pyresdiablo**
too many recipes :v

### CODE REVIEW

**Comment by theBowja** [comment]
Where did you get most of the information?

**Comment by pyresdiablo** [comment]
Mostly genshin.gg and gamewith.net.

**Comment by theBowja** [comment]
I'm gonna make some changes to the recipe template and update the existing recipes.
Is there a reason why you made the "recipe" property instead of just "ingredients"?

**Comment by pyresdiablo** [comment]
Sure, you can make the change.
I overlooked that. My bad.

**Pull request merged**
